#!/usr/bin/env python3
"""Copy the Hands crate into a grok-build checkout and register it."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

MEMBER = '    "crates/codegen/hands",'
OLD_MEMBER = '    "crates/codegen/grok-harness",'


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: inject.py <hands-repo> <grok-build-checkout>", file=sys.stderr)
        return 2
    src_repo = Path(sys.argv[1]).resolve()
    grok_build = Path(sys.argv[2]).resolve()
    crate_src = src_repo / "crate"
    dest = grok_build / "crates" / "codegen" / "hands"
    if not (crate_src / "Cargo.toml").is_file():
        print(f"missing crate at {crate_src}", file=sys.stderr)
        return 1
    old = grok_build / "crates" / "codegen" / "grok-harness"
    if old.exists():
        shutil.rmtree(old)
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(crate_src, dest)

    # Embed the exact Hands repository revision into the injected crate so a
    # real ChatGPT/MCP acceptance run can prove which source revision is
    # actually serving requests. Never guess when the source is not a git
    # checkout; keep the committed "unknown" fallback in that case.
    try:
        source_sha = subprocess.check_output(
            ["git", "-C", str(src_repo), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        dirty = subprocess.check_output(
            ["git", "-C", str(src_repo), "status", "--porcelain", "--untracked-files=no"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if dirty:
            source_sha = f"{source_sha}-dirty"
    except (OSError, subprocess.CalledProcessError):
        source_sha = ""
    if source_sha:
        provenance = dest / "src" / "build_provenance.rs"
        provenance.write_text(
            "// Generated by scripts/inject.py; do not edit in the injected copy.\n"
            f'pub const SOURCE_GIT_SHA: &str = "{source_sha}";\n',
            encoding="utf-8",
        )

    root = grok_build / "Cargo.toml"
    text = root.read_text()
    if OLD_MEMBER in text:
        text = text.replace(OLD_MEMBER, MEMBER, 1)
        root.write_text(text)
    elif MEMBER.strip() not in text:
        needle = '    "crates/codegen/xai-grok-tools",'
        if needle not in text:
            print("could not find xai-grok-tools member in grok-build Cargo.toml", file=sys.stderr)
            return 1
        text = text.replace(needle, needle + "\n" + MEMBER, 1)
        root.write_text(text)

    # On Windows, fix /dev/stdout and /dev/null in xai-proto-build if present
    proto_build_lib = grok_build / "crates" / "build" / "xai-proto-build" / "src" / "lib.rs"
    if sys.platform == "win32" and proto_build_lib.is_file():
        pb_text = proto_build_lib.read_text(encoding="utf-8")
        if "--dependency_out=/dev/stdout" in pb_text:
            old_block = '''        for proto in protos {
            let mut command = Command::new(protoc.unwrap_or(Path::new("protoc")));
            command
                .arg("--dependency_out=/dev/stdout")
                .arg("--descriptor_set_out=/dev/null");'''
            new_block = '''        for proto in protos {
            let tmp = tempfile::TempDir::new()?;
            let dep_file = tmp.path().join("deps.d");
            let desc_file = tmp.path().join("desc.pbbin");

            let mut command = Command::new(protoc.unwrap_or(Path::new("protoc")));
            command
                .arg(format!("--dependency_out={}", dep_file.display()))
                .arg(format!("--descriptor_set_out={}", desc_file.display()));'''
            old_parse = '''            let output =
                String::from_utf8(output.stdout).context("protoc command output not UTF-8")?;

            let mut lines = output.lines();
            let first_line = lines.next().context("protoc command output is empty")?;
            let prefix = "/dev/null:";
            let rem = first_line.strip_prefix(prefix).with_context(|| {
                format!("protoc command output must start with /dev/null: {output:?}")
            })?;'''
            new_parse = '''            let output = fs::read_to_string(&dep_file).context("read dependency file")?;

            let mut lines = output.lines();
            let first_line = lines.next().context("protoc command output is empty")?;
            let desc_str = desc_file.to_string_lossy();
            let rem = if let Some(r) = first_line.strip_prefix(desc_str.as_ref()) {
                r.strip_prefix(':').unwrap_or(r)
            } else if let Some((_, r)) = first_line.rsplit_once(':') {
                r
            } else {
                first_line
            };'''
            if old_block not in pb_text:
                print("inject: expected xai-proto-build seam not found (old_block missing); refusing half-patched write", file=sys.stderr)
                print("hint: upstream xai-proto-build src/lib.rs drifted; update inject.py seams", file=sys.stderr)
                return 1
            if old_parse not in pb_text:
                print("inject: expected xai-proto-build seam not found (old_parse missing); refusing half-patched write", file=sys.stderr)
                print("hint: upstream xai-proto-build src/lib.rs drifted; update inject.py seams", file=sys.stderr)
                return 1
            pb_text_after_block = pb_text.replace(old_block, new_block, 1)
            if new_block not in pb_text_after_block:
                print("inject: xai-proto-build patch failed (old_block replace did not apply)", file=sys.stderr)
                return 1
            pb_text = pb_text_after_block
            pb_text_after_parse = pb_text.replace(old_parse, new_parse, 1)
            if new_parse not in pb_text_after_parse:
                print("inject: xai-proto-build patch failed (old_parse replace did not apply); refusing half-patched write", file=sys.stderr)
                return 1
            pb_text = pb_text_after_parse
            proto_build_lib.write_text(pb_text, encoding="utf-8")
            print("patched xai-proto-build for Windows compatibility")
    print(f"injected {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
